name: demo_app
description: Demo app showcasing Flutter Product Factory architecture.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.8.0"

resolution: workspace

dependencies:
  counter_part:
  factory_analytics:
  factory_async:
  factory_http:
  factory_storage:
  factory_ui:
  feature_counter:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
