name: core
description: Core utilities â€” Failure type, Either typedefs, and common typedefs.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  fpdart: ^1.2.0
  freezed_annotation: ^3.0.0
  talker: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^3.0.0
